stages:
  - test
  - report

tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.41.1-jammy
  script:
    - npm ci
    - npx playwright test
  artifacts:    
    when: always
    paths:
      - allure-results

allure_report:    
  stage: report
  image: openjdk:11
  before_script:
    - apt-get update && apt-get install -y allure
    - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    - export PATH=$PATH:/root/.npm-global/bin
  script:
    - allure generate --clean allure-results/ -o allure-report --single-file
  artifacts:    
    paths:
      - allure-report/
    when: on_success
    expire_in: 30 days

