stages:
  - test
  - report

tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.41.1-jammy
  script:
    - npm ci
    - npx playwright test
  artifacts:    
    when: always
    paths:
      - allure-results
      - playwright-report

allure_report:    
  stage: report
  image: ondysss/allure
  script:
    - allure generate --clean allure-results/ -o allure-report --single-file
  artifacts:    
    paths:
      - allure-report/
    when: on_success
    expire_in: 30 days

